name: doit-using-github-actions
on: [push]
jobs:
  build-deploy-execute:
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      # had issues running under java 11 - so switched to java8
      - name: "Extract version from pom.xml"
        run: |
            cd my-app
            export MAJOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $1}')
            export MINOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $2}')
            export PATCH=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $3}')
            export PATCH=$((PATCH+1))
            export POMVERSION=$MAJOR.$MINOR.$PATCH
            echo "POMVERSION=$POMVERSION">savever.txt
            # Code can be nicer looking, but I prefer readbility over a very long bash code ...
            # saving version to file overcome M$ not sharing enviroment between steps ... M$.
            # more info in this thread https://github.community/t/support-saving-environment-variables-between-steps/16230
      - name: "Update POM, compile and create JAR file"
        run: |
            cd my-app
            source savever.txt
            mvn versions:set -DnewVersion=$POMVERSION
            # easy way to update the POM file.
            mvn compile
            mvn package
            ls -al target
            java -cp target/my-app-$POMVERSION.jar com.mycompany.app.App
      - uses: actions/upload-artifact@v2
        with:
            name: my-app-artifact
            path: my-app/target/my-app-*.jar
  Create_and_push_docker_continer:
    runs-on: ubuntu-20.04
    needs: build-deploy-execute
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: my-app-artifact
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Extract version from pom.xml- Yes, Again M$, this is a new job - so we do not have the version file saved ...
      # I could have used the github actions here, but I needed the version. I assume a nicer solution can be found/used.
      - name: "get Version, build docker, push, pull and execute app"
        run: |
            cd my-app
            export MAJOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $1}')
            export MINOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $2}')
            export PATCH=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $3}')
            export PATCH=$((PATCH+1))
            export POMVERSION=$MAJOR.$MINOR.$PATCH
            echo "POMVERSION=$POMVERSION">savever.txt
            cd ..
            docker build --tag icnaan/my-app:$POMVERSION --build-arg ver=$POMVERSION .
            docker images
            docker push icnaan/my-app:$POMVERSION
            # remove image to validate that the pull works.
            docker rmi icnaan/my-app:$POMVERSION -f
            docker pull icnaan/my-app:$POMVERSION
            docker run -it --name bond --rm -d icnaan/my-app:$POMVERSION /bin/bash
            docker ps
            docker exec bond java -cp /home/koko/my-app-$POMVERSION.jar com.mycompany.app.App
            docker stop bond
            docker ps
