name: doit-using-github-actions
on: [push]
jobs:
  build-deploy-execute:
    runs-on: ubuntu-20.04
    env:
        MAJOR: '1'
        MINOR: '0'
        PATCH: '0'
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: apt-get update
      - run: apt-get install -y maven
      - run: echo "version is $MAJOR.$MINOR.$PATCH"
      - run: |
            cd my-app
            mvn package
      - run: |
          cd my-app
          java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
      - uses: actions/upload-artifact@v2
        with:
            name: my-app-artifact
            path: my-app/target/my-app-1.0-SNAPSHOT.jar
