name: doit-using-github-actions
on: [push]
jobs:
  build-deploy-execute:
    runs-on: ubuntu-20.04
   
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: "Extract version from pom.xml"
        run: |
            cd my-app
            export MAJOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $1}')
            export MINOR=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $2}')
            export PATCH=$(cat pom.xml | grep "^  <version>.*</version>$" | awk -F'[><]' '{print $3}' |  awk -F '[.-]+' '{print $3}')
            export PATCH=$((PATCH+1))
            echo "PATCH is $PATCH"
            export POMVERSION=$MAJOR.$MINOR.$PATCH
            echo "POMVERSION=$POMVERSION">savever.txt
      - run: |
            source my-app/savever.txt
            echo "version is $POMVERSION"
            sed '/version/{s/.*/$POMVERSION/g}' -i my-app/pom.xml
      - run: |
            cd my-app
            mvn package
      - run: |
          cd my-app
          java -cp target/my-app-$MAJOR.$MINOR.$PATCH.jar com.mycompany.app.App
      - uses: actions/upload-artifact@v2
        with:
            name: my-app-artifact
            path: my-app/target/my-app-$MAJOR.$MINOR.$PATCH.jar
    
